In [ ]:
words = open('names.txt', 'r').read().splitlines()
len(words)

Bigram Language Model

In [ ]:
b = {}

for w in words:
    chs = ['<S>'] + list(w) + ['<E>']
    for ch1, ch2 in zip(chs, chs[1:]):
        bigram = (ch1, ch2)
        b[bigram] = b.get(bigram, 0) + 1

In [ ]:
sorted(b.items(), key = lambda kv: -kv[1])

In [ ]:
import torch

N = torch.zeros((27, 27), dtype=torch.int32)

In [ ]:
chars = sorted(list(set(''.join(words))))
s_to_i = {s:i+1 for i,s in enumerate(chars)}
s_to_i['.'] = 0

i_to_s = {i:s for s,i in s_to_i.items()}

In [ ]:
for w in words:
    chs = ['.'] + list(w) + ['.']
    for ch1, ch2 in zip(chs, chs[1:]):
        ix1 = s_to_i[ch1]
        ix2 = s_to_i[ch2]

        N[ix1, ix2] += 1

In [ ]:
import matplotlib.pyplot as plt

plt.figure(figsize=(16,16))
plt.imshow(N, cmap='Blues')
for i in range(27):
    for j in range(27):
        chstr = i_to_s[i] + i_to_s[j]
        plt.text(j, i, chstr, ha="center", va="bottom", color='gray')
        plt.text(j, i, N[i, j].item(), ha="center", va="top", color='gray')
plt.axis('off');

In [ ]:
p = N[0].float()
p /= p.sum()
p

In [ ]:
g = torch.Generator().manual_seed(2147483647)
ix = torch.multinomial(p, num_samples=1, replacement=True, generator=g).item()
i_to_s[ix]

In [ ]:
g = torch.Generator().manual_seed(2147483647)
p = torch.rand(3, generator=g)
p /= p.sum()
p

In [ ]:
torch.multinomial(p, num_samples=20, replacement=True, generator=g)

In [ ]:
P = (N+1).float()
P /= P.sum(1, keepdim=True)



In [71]:
g = torch.Generator().manual_seed(2147483647)

for i in range(50):
    out = []
    ix = 0

    while True:

        p = P[ix]
        # p = N[ix].float()
        # p /= p.sum()
        ix = torch.multinomial(p, num_samples=1, replacement=True, generator=g).item()
        out.append(i_to_s[ix])

        if ix == 0:
            break

    print(''.join(out[:-1]))

cexze
momasurailezitynn
konimittain
llayn
ka
da
staiyaubrtthrigotai
moliellavo
ke
teda
ka
emimmsade
enkaviyny
ftlspihinivenvorhlasu
dsor
br
jol
pen
aisan
ja
feniee
zem
deru
firit
gaikajahahbevare
kiysthelenaririenah
keen
x
al
kal
thavazeeromysos
laitenimieegariseriyen
k
illeleldole
meenisammigama
mmin
asharin
alcalar
jayn
asaz
selanely
chay
rana
ai
yviamisashougen
l
beyncaro
allan
annutetoradrilia
rddeman


In [57]:
log_likelihood = 0.0
n = 0

for w in words:
    chs = ['.'] + list(w) + ['.']
    for ch1, ch2 in zip(chs, chs[1:]):
        ix1 = s_to_i[ch1]
        ix2 = s_to_i[ch2]

        prob = P[ix1, ix2]
        logprob = torch.log(prob)
        log_likelihood += logprob
        n += 1
        #print(f'{ch1}{ch2}: {prob:.4f} {logprob:.4f}')

print(f'{log_likelihood=}')
nll = -log_likelihood
print(f'{nll=}')
print(f'{nll/n=}')

log_likelihood=tensor(-559951.5625)
nll=tensor(559951.5625)
nll/n=tensor(2.4544)


In [70]:
P

tensor([[3.1192e-05, 1.3759e-01, 4.0767e-02, 4.8129e-02, 5.2745e-02, 4.7785e-02,
         1.3038e-02, 2.0898e-02, 2.7293e-02, 1.8465e-02, 7.5577e-02, 9.2452e-02,
         4.9064e-02, 7.9195e-02, 3.5777e-02, 1.2321e-02, 1.6095e-02, 2.9008e-03,
         5.1154e-02, 6.4130e-02, 4.0830e-02, 2.4641e-03, 1.1759e-02, 9.6070e-03,
         4.2109e-03, 1.6719e-02, 2.9008e-02],
        [1.9583e-01, 1.6425e-02, 1.5983e-02, 1.3889e-02, 3.0756e-02, 2.0435e-02,
         3.9809e-03, 4.9835e-03, 6.8796e-02, 4.8685e-02, 5.1899e-03, 1.6779e-02,
         7.4575e-02, 4.8213e-02, 1.6039e-01, 1.8872e-03, 2.4475e-03, 1.7988e-03,
         9.6279e-02, 3.2997e-02, 2.0288e-02, 1.1264e-02, 2.4623e-02, 4.7771e-03,
         5.3963e-03, 6.0480e-02, 1.2857e-02],
        [4.3039e-02, 1.2051e-01, 1.4596e-02, 7.4850e-04, 2.4701e-02, 2.4551e-01,
         3.7425e-04, 3.7425e-04, 1.5719e-02, 8.1587e-02, 7.4850e-04, 3.7425e-04,
         3.8922e-02, 3.7425e-04, 1.8713e-03, 3.9671e-02, 3.7425e-04, 3.7425e-04,
         3.1549e-

In [54]:
xs, ys = [], []

for w in words[:2]:
    chs = ['.'] + list(w) + ['.']
    for ch1, ch2 in zip(chs, chs[1:]):
        ix1 = s_to_i[ch1]
        ix2 = s_to_i[ch2]
        xs.append(ix1)
        ys.append(ix2)

xs = torch.tensor(xs)
ys = torch.tensor(ys)


In [55]:
xs, ys

(tensor([ 0,  5, 13, 13,  1,  0, 15, 12,  9, 22,  9,  1]),
 tensor([ 5, 13, 13,  1,  0, 15, 12,  9, 22,  9,  1,  0]))

In [ ]:
import torch.nn.functional as F

xenc = F.one_hot(xs, num_classes=27).float()
xenc

In [ ]:
plt.imshow(xenc)

In [ ]:
g = torch.Generator().manual_seed(2147483647 + 1)
W = torch.randn((27, 27), generator=g)

W = torch.randn((27, 27))
logits = (xenc @ W)
counts = logits.exp()
probs = counts / counts.sum(1, keepdim=True)
probs

In [ ]:
nlls = torch.zeros(5)
for i in range(5):
    # i-th bigram:
    x = xs[i].item() # input character index
    y = ys[i].item() # label character index
    print('--------')
    print(f'bigram example {i+1}: {i_to_s[x]}{i_to_s[y]} (indexes {x},{y})')
    print('input to the neural net:', x)
    print('output probabilities from the neural net:', probs[i])
    print('label (actual next character):', y)
    p = probs[i, y]
    print('probability assigned by the net to the the correct character:', p.item())
    logp = torch.log(p)
    print('log likelihood:', logp.item())
    nll = -logp
    print('negative log likelihood:', nll.item())
    nlls[i] = nll

print('=========')
print('average negative log likelihood, i.e. loss =', nlls.mean().item())

In [50]:
xs

tensor([ 0,  5, 13,  ..., 25, 26, 24])

In [ ]:
ys

In [ ]:
g = torch.Generator().manual_seed(2147483647)
W = torch.randn((27, 27), generator=g, requires_grad=True)

In [48]:
xenc = F.one_hot(xs, num_classes=27).float()
logits = (xenc @ W)
counts = logits.exp()
probs = counts / counts.sum(1, keepdim=True)
probs


tensor([[0.0007, 0.1376, 0.0407,  ..., 0.0042, 0.0167, 0.0290],
        [0.1950, 0.0332, 0.0059,  ..., 0.0064, 0.0524, 0.0088],
        [0.0766, 0.3889, 0.0154,  ..., 0.0022, 0.0421, 0.0020],
        ...,
        [0.2050, 0.2189, 0.0029,  ..., 0.0031, 0.0031, 0.0074],
        [0.0624, 0.3550, 0.0030,  ..., 0.0056, 0.0565, 0.0157],
        [0.2236, 0.1203, 0.0098,  ..., 0.0346, 0.0210, 0.0297]],
       grad_fn=<DivBackward0>)

In [56]:
probs[0, 5], probs[1, 13], probs[2, 13], probs[3, 1], probs[4, 0]

(tensor(0.0478, grad_fn=<SelectBackward0>),
 tensor(0.0376, grad_fn=<SelectBackward0>),
 tensor(0.0240, grad_fn=<SelectBackward0>),
 tensor(0.3889, grad_fn=<SelectBackward0>),
 tensor(0.1959, grad_fn=<SelectBackward0>))

In [49]:
loss = -probs[torch.arange(5), ys].log().mean()
loss

IndexError: shape mismatch: indexing tensors could not be broadcast together with shapes [5], [228146]

In [32]:
print(loss.item())

3.7693049907684326


In [35]:
W.grad = None
loss.backward()

In [36]:
W.data += -0.1 * W.grad

In [41]:
# ---------- !!! OPTIMIZATION !!! yay, but this time actually --------------

# create the dataset
xs, ys = [], []
for w in words:
    chs = ['.'] + list(w) + ['.']
    for ch1, ch2 in zip(chs, chs[1:]):
        ix1 = s_to_i[ch1]
        ix2 = s_to_i[ch2]
        xs.append(ix1)
        ys.append(ix2)
xs = torch.tensor(xs)
ys = torch.tensor(ys)
num = xs.nelement()
print('number of examples: ', num)

# initialize the 'network'
g = torch.Generator().manual_seed(2147483647)
W = torch.randn((27, 27), generator=g, requires_grad=True)

number of examples:  228146


In [46]:
# gradient descent
for k in range(100):

    # forward pass
    xenc = F.one_hot(xs, num_classes=27).float() # input to the network: one-hot encoding
    logits = xenc @ W # predict log-counts
    counts = logits.exp() # counts, equivalent to N
    probs = counts / counts.sum(1, keepdims=True) # probabilities for next character
    loss = -probs[torch.arange(num), ys].log().mean()
    print(loss.item())

    # backward pass
    W.grad = None # set to zero the gradient
    loss.backward()

    # update
    W.data += -50 * W.grad

2.472180128097534
2.4719715118408203
2.4717674255371094
2.4715678691864014
2.47137188911438
2.4711804389953613
2.4709928035736084
2.470808982849121
2.4706287384033203
2.470452070236206
2.4702789783477783
2.470109224319458
2.469942808151245
2.4697797298431396
2.4696195125579834
2.4694626331329346
2.469308614730835
2.4691574573516846
2.4690089225769043
2.4688637256622314
2.4687206745147705
2.4685797691345215
2.468442440032959
2.4683070182800293
2.4681739807128906
2.468043565750122
2.4679150581359863
2.4677889347076416
2.467664957046509
2.467543363571167
2.467423439025879
2.467306137084961
2.4671905040740967
2.467076539993286
2.4669642448425293
2.4668543338775635
2.4667460918426514
2.466639757156372
2.4665346145629883
2.4664316177368164
2.466330051422119
2.4662299156188965
2.4661316871643066
2.4660348892211914
2.465939521789551
2.4658455848693848
2.4657528400421143
2.4656620025634766
2.4655721187591553
2.4654839038848877
2.4653966426849365
2.46531081199646
2.465226650238037
2.465142965316